table david_final_topic_analysis
	lineageTag: db7e22b5-5f9f-485a-99c2-af07f03e1723

	column topic
		dataType: string
		lineageTag: 49872c33-305a-4818-9eb3-d5d795ab52a7
		summarizeBy: none
		sourceColumn: topic

		annotation SummarizationSetBy = Automatic

	column review_count
		dataType: double
		lineageTag: 5e65f695-616d-49c7-a333-9467ed42442e
		summarizeBy: sum
		sourceColumn: review_count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column share_pct
		dataType: double
		lineageTag: 5eade00d-577d-4c93-94cb-81195b90274f
		summarizeBy: sum
		sourceColumn: share_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column negative_reviews
		dataType: double
		lineageTag: 11ebf80b-c38b-49bb-a0ec-c715f7358d97
		summarizeBy: sum
		sourceColumn: negative_reviews

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column negative_rate_pct
		dataType: double
		lineageTag: 7724bba7-1e17-4e8b-9f67-0ee80598dc12
		summarizeBy: sum
		sourceColumn: negative_rate_pct

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_review_score
		dataType: double
		lineageTag: febfa9d9-b2ca-453a-92e8-8913f536b694
		summarizeBy: sum
		sourceColumn: avg_review_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column negative_contribution_pct
		dataType: double
		lineageTag: 87a65c90-7cab-4f78-b473-2c2b70cffe19
		summarizeBy: sum
		sourceColumn: negative_contribution_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition david_final_topic_analysis = m
		mode: import
		source =
				let
				  Quelle = Csv.Document(File.Contents("C:\Users\bigd\Desktop\DSI - Weiterbildung\olist_marketplace_analysis\olist-marketplace-analysis\datasets\processed\final_topic_analysis.csv"), [Delimiter = ",", Columns = 8, QuoteStyle = QuoteStyle.None]),
				  #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars = true]),
				    #"Entfernte Spalten" = Table.RemoveColumns(#"Höher gestufte Header",{"priority_score"}),
				    #"Geänderter Typ mit Gebietsschema" = Table.TransformColumnTypes(#"Entfernte Spalten", {{"review_count", type number}, {"share_pct", type number}, {"negative_reviews", type number}, {"negative_rate_pct", type number}, {"avg_review_score", type number}, {"negative_contribution_pct", type number}}, "en-US")
				in
				    #"Geänderter Typ mit Gebietsschema"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

