table david_fact_comment_topics
	lineageTag: 19851424-e87f-45c9-bf38-a8aa424c7361

	column id_order_reviews
		dataType: int64
		formatString: 0
		lineageTag: b57fe0bc-5b3b-431f-8346-40ce0fdb7f03
		summarizeBy: sum
		sourceColumn: id_order_reviews

		annotation SummarizationSetBy = Automatic

	column review_id
		dataType: string
		lineageTag: 5d2bc4cd-e0f6-46d4-8d37-b565aa9edf5e
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 599f2fc6-3f77-4ac0-9d15-28228066fe91
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: 7707cefd-1829-48a0-8491-3c94c4cb1235
		summarizeBy: sum
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column review_comment_message_en
		dataType: string
		lineageTag: 7f104f59-c8b3-491c-830d-ca54a141e536
		summarizeBy: none
		sourceColumn: review_comment_message_en

		annotation SummarizationSetBy = Automatic

	column topic
		dataType: string
		lineageTag: 67266c30-5eef-4ba6-8632-fda54bc2b800
		summarizeBy: none
		sourceColumn: topic

		annotation SummarizationSetBy = Automatic

	column is_negative
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a00b344e-f906-4e9d-b1fd-be759443fffc
		summarizeBy: none
		sourceColumn: is_negative

		annotation SummarizationSetBy = Automatic

	partition david_fact_comment_topics = m
		mode: import
		source =
				let
				  Quelle = Csv.Document(File.Contents("C:\Users\bigd\Desktop\DSI - Weiterbildung\olist_marketplace_analysis\olist-marketplace-analysis\datasets\processed\comment_topics.csv"), [Delimiter = ",", Columns = 7, QuoteStyle = QuoteStyle.None]),
				  #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars = true]),
				  #"Geänderter Spaltentyp" = Table.TransformColumnTypes(#"Höher gestufte Header", {{"id_order_reviews", Int64.Type}, {"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_message_en", type text}, {"topic", type text}, {"is_negative", type logical}}, "de")
				in
				  #"Geänderter Spaltentyp"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

